FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# Tenistas

## Tenistas [/tenistas/tenistas_list]

### List All Tenistas [GET]

+ Response 200 (application/json)

        [
            {
                "id": "21357",
                "thumbnail": "https://www.tennismagazin.de/content/uploads/2019/04/alcaraz_nadal-1024x579.jpg",
                "Nombre": "Carlos"
                "Apellidos":"Alcaraz Garfia"
            },{
                "id": "98746",
                "thumbnail": "https://image-cdn.essentiallysports.com/wp-content/uploads/20200225232344/Novak-Djokovic-4-1600x1200.jpg",
                "Nombre": "Novak"
                "Apellidos":"Djokovic"
            },{
                "id": "102576",
                "thumbnail": "https://wallpapercave.com/wp/wp8890334.jpg",
                "Nombre": "Daniil"
                "Apellidos":"Medvedev"
            },{
                "id": "33641",
                "thumbnail": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Rune_RG22_(4)_(52144534990).jpg/640px-Rune_RG22_(4)_(52144534990).jpg",
                "Nombre": "Holger"
                "Apellidos":"Rune"
            },{
                "id": "322458",
                "thumbnail": "https://images.neobookings.com/cms/rafanadalacademy.com/section/casper-ruud-acaricia-su-primer-titulo-atp/pics/casper-ruud-acaricia-su-primer-titulo-atp-em6rv8l4gn.jpg",
                "Nombre": "Casper"
                "Apellidos":"Ruud"
            },{
                "id": "877754",
                "thumbnail": "https://sportsgroup.pl/images/bg/iga-swiatek_1920x1080dd.jpg",
                "Nombre": "Iga"
                "Apellidos":"Swiatek"
            },{
                "id": "410150",
                "thumbnail": "https://images.tennis.com/image/private/t_q-best/tenniscom-prd/xsbvgbjlb65fzygqcy7a.jpg",
                "Nombre": "Aryna"
                "Apellidos":"Sabalenka"
            },{
                "id": "5036954",
                "thumbnail": "https://www.tennismajors.com/app/uploads/2021/02/panoramic_PANOAUSTENNIS09022021_043.jpg",
                "Nombre": "Jessica"
                "Apellidos":"Pegula"
            },{
                "id": "420350",
                "thumbnail": "https://firstsportz.com/wp-content/uploads/2021/07/rybakina.jpg",
                "Nombre": "Elena"
                "Apellidos":"Rybakina"
            },{
                "id": "810575",
                "thumbnail": "https://www.hawtcelebs.com/wp-content/uploads/2018/10/ons-jabeur-at-2018-vtb-kremlin-cup-international-in-moscow-10-17-2018-4.jpg",
                "Nombre": "Ons"
                "Apellidos":"Jabeur"
            }
        ]

## Tenista 21357 [/Tenistas/tenista_detail/21357]

### Get tenista detail 21357 [GET]

+ Response 200 (application/json)

        
        {
           "Edad (años)":"20"
           "Nacionalidad": "Español"
           "Estatura (m)":"1.85"
           "Ranking ATP (WTA)":"1"
           "Puntos":"9815"
           "Torneos ATP (WTA) ganados":"12"
           "Ingresos totales (dll)":"17320448"
        }
        
## Tenista 98746 [/tenistas/tenista_detail/98746]

### Get tenista detail 98746 [GET]

+ Response 200 (application/json)

        
        {
            "Edad (años)":"36"
            "Nacionalidad": "Serbio"
            "Estatura (m)":"1.82"
            "Ranking ATP (WTA)":"2"
            "Puntos":"9795"
            "Torneos ATP (WTA) ganados":"95"
            "Ingresos totales (dll)":"172281484"
        }

## Tenista 102576 [/tenistas/tenista_detail/102576]

### Get tenista detail 102576 [GET]

+ Response 200 (application/json)

        
        {
            "Edad (años)":"27"
            "Nacionalidad": "Ruso"
            "Estatura (m)":"1.98"
            "Ranking ATP (WTA)":"3"
            "Puntos":"6260"
            "Torneos ATP (WTA) ganados":"20"
            "Ingresos totales (dll)":"26600381"
        }
        
## Tenista 33641 [/tenistas/tenista_detail/33641]

### Get tenista detail 33641 [GET]

+ Response 200 (application/json)

        
        {
            "Edad (años)":"20"
            "Nacionalidad": "Danés"
            "Estatura (m)":"1.88"
            "Ranking ATP (WTA)":"4"
            "Puntos":"4790"
            "Torneos ATP (WTA) ganados":"4"
            "Ingresos totales (dll)":"2767278"
        }
        
## Tenista 322458 [/tenistas/tenista_detail/322458]

### Get tenista detail 322458 [GET]

+ Response 200 (application/json)

        
        {
            "Edad (años)":"22"
            "Nacionalidad": "Noruego"
            "Estatura (m)":"1.83"
            "Ranking ATP (WTA)":"5"
            "Puntos":"4715"
            "Torneos ATP (WTA) ganados":"10"
            "Ingresos totales (dll)":"13571989"
        }
        
## Tenista 877754 [/tenistas/tenista_detail/877754]

### Get tenista detail 877754 [GET]

+ Response 200 (application/json)

        
        {
            "Edad (años)":"22"
            "Nacionalidad": "Polaca"
            "Estatura (m)":"1.76"
            "Ranking ATP (WTA)":"1"
            "Puntos":"9955"
            "Torneos ATP (WTA) ganados":"15"
            "Ingresos totales (dll)":"19630763"
        }
        
## Tenista 410150 [/tenistas/tenista_detail/410150]

### Get tenista detail 410150 [GET]

+ Response 200 (application/json)

        
        {
            "Edad (años)":"25"
            "Nacionalidad": "Bielorusa"
            "Estatura (m)":"1.82"
            "Ranking ATP (WTA)":"2"
            "Puntos":"8746"
            "Torneos ATP (WTA) ganados":"13"
            "Ingresos totales (dll)":"17874895"
        }
        
## Tenista 5036954 [/tenistas/tenista_detail/5036954]

### Get tenista detail 5036954 [GET]

+ Response 200 (application/json)

        
        {
            "Edad (años)":"29"
            "Nacionalidad": "Estadounidense"
            "Estatura (m)":"1.70"
            "Ranking ATP (WTA)":"3"
            "Puntos":"5945"
            "Torneos ATP (WTA) ganados":"3"
            "Ingresos totales (dll)":"10184118"
        }
        
## Tenista 420350 [/tenistas/tenista_detail/420350]

### Get tenista detail 420350 [GET]

+ Response 200 (application/json)

        
        {
            "Edad (años)":"24"
            "Nacionalidad": "Kazajistán"
            "Estatura (m)":"1.84"
            "Ranking ATP (WTA)":"4"
            "Puntos":"5670"
            "Torneos ATP (WTA) ganados":"5"
            "Ingresos totales (dll)":"10695745"
        }
        
## Tenista 810575 [/tenistas/tenista_detail/810575]

### Get tenista detail 810575 [GET]

+ Response 200 (application/json)

        
        {
            "Edad (años)":"29"
            "Nacionalidad": "Tunecina"
            "Estatura (m)":"1.67"
            "Ranking ATP (WTA)":"5"
            "Puntos":"4831"
            "Torneos ATP (WTA) ganados":"4"
            "Ingresos totales (dll)":"11509857"
        }