FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# Tenistas

## Tenistas [/tenistas/tenistas_list]

### List All Tenistas [GET]

+ Response 200 (application/json)

        [
            {
                "id": "21357",
                "thumbnail": "https://www.tennismagazin.de/content/uploads/2019/04/alcaraz_nadal-1024x579.jpg",
                "Nombre": "Carlos"
                "Apellidos":"Alcaraz Garfia"
            },{
                "id": "98746",
                "thumbnail": "https://image-cdn.essentiallysports.com/wp-content/uploads/20200225232344/Novak-Djokovic-4-1600x1200.jpg",
                "Nombre": "Novak"
                "Apellidos":"Djokovic"
            },{
                "id": "102576",
                "thumbnail": "https://wallpapercave.com/wp/wp8890334.jpg",
                "Nombre": "Daniil"
                "Apellidos":"Medvedev"
            },{
                "id": "33641",
                "thumbnail": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Rune_RG22_(4)_(52144534990).jpg/640px-Rune_RG22_(4)_(52144534990).jpg",
                "Nombre": "Holger"
                "Apellidos":"Rune"
            },{
                "id": "322458",
                "thumbnail": "https://images.neobookings.com/cms/rafanadalacademy.com/section/casper-ruud-acaricia-su-primer-titulo-atp/pics/casper-ruud-acaricia-su-primer-titulo-atp-em6rv8l4gn.jpg",
                "Nombre": "Casper"
                "Apellidos":"Ruud"
            },{
                "id": "877754",
                "thumbnail": "https://www.serverbpw.com/cm/games/imgs/sbrost.png",
                "Nombre": ""
                "Apellidos":""
            },{
                "id": "410150",
                "thumbnail": "https://www.serverbpw.com/cm/games/imgs/minecraftt.png",
                "Nombre": ""
                "Apellidos":""
            },{
                "id": "5036954",
                "thumbnail": "https://www.serverbpw.com/cm/games/imgs/zeldasst.png",
                "Nombre": ""
                "Apellidos":""
            }
        ]

## Tenista 21357 [/Tenistas/tenista_detail/21357]

### Get tenista detail 21357 [GET]

+ Response 200 (application/json)

        
        {
           "Edad (años)":"20"
           "Nacionalidad": "Español"
           "Estatura (m)":"1.85"
           "Ranking ATP":"1"
           "Puntos":"9815"
           "Torneos ATP ganados":"12"
           "Ingresos totales (dll)":"17320448"
        }
        
## Tenista 98746 [/tenistas/tenista_detail/98746]

### Get tenista detail 98746 [GET]

+ Response 200 (application/json)

        
        {
            "Edad (años)":""
            "Nacionalidad": ""
            "Estatura (m)":""
            "Ranking ATP":""
            "Puntos":""
            "Torneos ATP ganados":""
            "Ingresos totales (dll)":""
        }

## Tenista 102576 [/tenistas/tenista_detail/102576]

### Get tenista detail 102576 [GET]

+ Response 200 (application/json)

        
        {
            "Edad (años)":""
            "Nacionalidad": ""
            "Estatura (m)":""
            "Ranking ATP":""
            "Puntos":""
            "Torneos ATP ganados":""
            "Ingresos totales (dll)":""
        }
        
## Tenista 33641 [/tenistas/tenista_detail/33641]

### Get tenista detail 33641 [GET]

+ Response 200 (application/json)

        
        {
            "Edad (años)":""
            "Nacionalidad": ""
            "Estatura (m)":""
            "Ranking ATP":""
            "Puntos":""
            "Torneos ATP ganados":""
            "Ingresos totales (dll)":""
        }
        
## Tenista 322458 [/tenistas/tenista_detail/322458]

### Get tenista detail 322458 [GET]

+ Response 200 (application/json)

        
        {
            "Edad (años)":""
            "Nacionalidad": ""
            "Estatura (m)":""
            "Ranking ATP":""
            "Puntos":""
            "Torneos ATP ganados":""
            "Ingresos totales (dll)":""
        }
        
## Tenista 877754 [/tenistas/tenista_detail/877754]

### Get tenista detail 877754 [GET]

+ Response 200 (application/json)

        
        {
            "Edad (años)":""
            "Nacionalidad": ""
            "Estatura (m)":""
            "Ranking ATP":""
            "Puntos":""
            "Torneos ATP ganados":""
            "Ingresos totales (dll)":""
        }
        
## Tenista 410150 [/tenistas/tenista_detail/410150]

### Get tenista detail 410150 [GET]

+ Response 200 (application/json)

        
        {
            "Edad (años)":""
            "Nacionalidad": ""
            "Estatura (m)":""
            "Ranking ATP":""
            "Puntos":""
            "Torneos ATP ganados":""
            "Ingresos totales (dll)":""
        }
        
## Tenista 5036954 [/tenistas/tenista_detail/5036954]

### Get tenista detail 5036954 [GET]

+ Response 200 (application/json)

        
        {
            "Edad (años)":""
            "Nacionalidad": ""
            "Estatura (m)":""
            "Ranking ATP":""
            "Puntos":""
            "Torneos ATP ganados":""
            "Ingresos totales (dll)":""
        }