FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# Tenistas

## Tenistas [/tenistas/tenistas_list]

### List All Tenistas [GET]

+ Response 200 (application/json)

        [
            {
                "thumbnail": "https://www.tennismagazin.de/content/uploads/2019/04/alcaraz_nadal-1024x579.jpg",
                "id": "21357",
                "Nombre": "Carlos",
                "Apellido":"Alcaraz Garfia",
                "Edad":"20"
            },{
                "thumbnail": "https://image-cdn.essentiallysports.com/wp-content/uploads/20200225232344/Novak-Djokovic-4-1600x1200.jpg",
                "id": "98746",
                "Nombre": "Novak",
                "Apellido":"Djokovic",
                "Edad":"36"
            },{
                "thumbnail": "https://wallpapercave.com/wp/wp8890334.jpg",
                "id": "102576",
                "Nombre": "Daniil",
                "Apellido":"Medvedev",
                "Edad":"27"
            },{
                "thumbnail": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Rune_RG22_(4)_(52144534990).jpg/640px-Rune_RG22_(4)_(52144534990).jpg",
                "id": "33641",
                "Nombre": "Holger",
                "Apellido":"Rune",
                "Edad":"20"
            },{
                "thumbnail": "https://images.neobookings.com/cms/rafanadalacademy.com/section/casper-ruud-acaricia-su-primer-titulo-atp/pics/casper-ruud-acaricia-su-primer-titulo-atp-em6rv8l4gn.jpg",
                "id": "322458",
                "Nombre": "Casper",
                "Apellido":"Ruud",
                "Edad":"22"
            },{
                "thumbnail": "https://sportsgroup.pl/images/bg/iga-swiatek_1920x1080dd.jpg",
                "id": "877754",
                "Nombre": "Iga",
                "Apellido":"Swiatek",
                "Edad":"22"
            },{
                "thumbnail": "https://images.tennis.com/image/private/t_q-best/tenniscom-prd/xsbvgbjlb65fzygqcy7a.jpg",
                "id": "410150",
                "Nombre": "Aryna",
                "Apellido":"Sabalenka",
                "Edad":"25"
            },{
                "thumbnail": "https://www.tennismajors.com/app/uploads/2021/02/panoramic_PANOAUSTENNIS09022021_043.jpg",
                "id": "5036954",
                "Nombre": "Jessica",
                "Apellido":"Pegula",
                "Edad":"29"
            },{
                "thumbnail": "https://firstsportz.com/wp-content/uploads/2021/07/rybakina.jpg",
                "id": "420350",
                "Nombre": "Elena",
                "Apellido":"Rybakina",
                "Edad":"24"
            },{
                "thumbnail": "https://www.hawtcelebs.com/wp-content/uploads/2018/10/ons-jabeur-at-2018-vtb-kremlin-cup-international-in-moscow-10-17-2018-4.jpg",
                "id": "810575",
                "Nombre": "Ons",
                "Apellido":"Jabeur",
                "Edad":"29"
            }
        ]

## Tenista 21357 [/tenistas/tenista_detail/21357]

### Get tenista detail 21357 [GET]

+ Response 200 (application/json)

        
        {
           "imagen": "https://www.tennismagazin.de/content/uploads/2019/04/alcaraz_nadal-1024x579.jpg",
           "Pais": "España",
           "Estatura":"1.85",
           "Ranking":"1",
           "Puntos":"9815",
           "Titulos":"12",
           "Ingresos_totales":"17320448",
           "Video": "https://drive.google.com/uc?id=1zMXVDAyOp6liwuwDK_Npc10LvvGPMEeL"
        }
        
## Tenista 98746 [/tenistas/tenista_detail/98746]

### Get tenista detail 98746 [GET]

+ Response 200 (application/json)

        
        {
            "imagen": "https://image-cdn.essentiallysports.com/wp-content/uploads/20200225232344/Novak-Djokovic-4-1600x1200.jpg",
            "Pais": "Serbia",
            "Estatura":"1.82",
            "Ranking":"2",
            "Puntos":"9795",
            "Titulos":"95",
            "Ingresos_totales":"172281484",
            "Video": "https://drive.google.com/uc?id=1rAjm7vPT8EBEIQ2hCVA-W_lnMfWTR4Vc"
        }

## Tenista 102576 [/tenistas/tenista_detail/102576]

### Get tenista detail 102576 [GET]

+ Response 200 (application/json)

        
        {
            "imagen": "https://wallpapercave.com/wp/wp8890334.jpg",
            "Pais": "Rusia",
            "Estatura":"1.98",
            "Ranking":"3",
            "Puntos":"6260",
            "Titulos":"20",
            "Ingresos_totales":"26600381",
            "Video": "https://drive.google.com/uc?id=1B4cmZdoktf0-Rhiw6WQ9WfaTchTBqehi"
        }
        
## Tenista 33641 [/tenistas/tenista_detail/33641]

### Get tenista detail 33641 [GET]

+ Response 200 (application/json)

        
        {
            "imagen": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Rune_RG22_(4)_(52144534990).jpg/640px-Rune_RG22_(4)_(52144534990).jpg",
            "Pais": "Dinamarca",
            "Estatura":"1.88",
            "Ranking":"4",
            "Puntos":"4790",
            "Titulos":"4",
            "Ingresos_totales":"2767278",
            "Video": "https://drive.google.com/uc?id=1Bxemn_RdvcQY1bQe5mUGh0JD2qGcDi8e"
        }
        
## Tenista 322458 [/tenistas/tenista_detail/322458]

### Get tenista detail 322458 [GET]

+ Response 200 (application/json)

        
        {
            "imagen": "https://images.neobookings.com/cms/rafanadalacademy.com/section/casper-ruud-acaricia-su-primer-titulo-atp/pics/casper-ruud-acaricia-su-primer-titulo-atp-em6rv8l4gn.jpg",
            "Pais": "Noruega",
            "Estatura":"1.83",
            "Ranking":"5",
            "Puntos":"4715",
            "Titulos":"10",
            "Ingresos_totales":"13571989",
            "Video": "https://drive.google.com/uc?id=14QItYkbJj028xAwTbJ2RTT5ffjpcHp74"
        }
        
## Tenista 877754 [/tenistas/tenista_detail/877754]

### Get tenista detail 877754 [GET]

+ Response 200 (application/json)

        
        {
            "imagen": "https://sportsgroup.pl/images/bg/iga-swiatek_1920x1080dd.jpg",
            "Pais": "Polonia",
            "Estatura":"1.76",
            "Ranking":"1",
            "Puntos":"9955",
            "Titulos":"15",
            "Ingresos_totales":"19630763",
            "Video": "https://drive.google.com/uc?id=1W7Lh5x_UEtOpbu0NBwHYUe6-4MOpmz0G"
        }
        
## Tenista 410150 [/tenistas/tenista_detail/410150]

### Get tenista detail 410150 [GET]

+ Response 200 (application/json)

        
        {
            "imagen": "https://images.tennis.com/image/private/t_q-best/tenniscom-prd/xsbvgbjlb65fzygqcy7a.jpg",
            "Pais": "Bielorusia",
            "Estatura":"1.82",
            "Ranking":"2",
            "Puntos":"8746",
            "Titulos":"13",
            "Ingresos_ totales (dll)":"17874895",
            "Video": "https://drive.google.com/uc?id=16dPbpc1-gDTqnS_6fhvCJPqO4VySJG4q"
        }
        
## Tenista 5036954 [/tenistas/tenista_detail/5036954]

### Get tenista detail 5036954 [GET]

+ Response 200 (application/json)

        
        {
            "imagen": "https://www.tennismajors.com/app/uploads/2021/02/panoramic_PANOAUSTENNIS09022021_043.jpg",
            "Pais": "USA",
            "Estatura (m)":"1.70",
            "Ranking ATP (WTA)":"3",
            "Puntos":"5945",
            "Titulos ATP (WTA)":"3",
            "Ingresos totales (dll)":"10184118",
            "Video": "https://drive.google.com/uc?id=1D_jM7u_pODgufjHAZzO9U5VQ6c91ZsFx"
        }
        
## Tenista 420350 [/tenistas/tenista_detail/420350]

### Get tenista detail 420350 [GET]

+ Response 200 (application/json)

        
        {
            "imagen": "https://firstsportz.com/wp-content/uploads/2021/07/rybakina.jpg",
            "Pais": "Kazajistán",
            "Estatura (m)":"1.84",
            "Ranking ATP (WTA)":"4",
            "Puntos":"5670",
            "Titulos ATP (WTA)":"5",
            "Ingresos totales (dll)":"10695745",
            "Video": "https://drive.google.com/uc?id=1yzV2ZJrZVEaj8iGaurPEWJ7g0WLN6CWU"
        }
        
## Tenista 810575 [/tenistas/tenista_detail/810575]

### Get tenista detail 810575 [GET]

+ Response 200 (application/json)

        
        {
            "imagen": "https://www.hawtcelebs.com/wp-content/uploads/2018/10/ons-jabeur-at-2018-vtb-kremlin-cup-international-in-moscow-10-17-2018-4.jpg",
            "Pais": "Túnez",
            "Estatura (m)":"1.67",
            "Ranking ATP (WTA)":"5",
            "Puntos":"4831",
            "Titulos ATP (WTA)":"4",
            "Ingresos totales (dll)":"11509857",
            "Video": "https://drive.google.com/uc?id=1MYOB62WSumC7i4v-6Xl9hbMkod7FPu_e"
        }